# Docker-compose setup for local development. This allows for a user
# to modify the pacer worker code and run tests in the Docker
# container without needing to rebuild/restart Docker.
#
# Usage:
#   docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build

services:
  web: # main haystack application
    container_name: pacer_web
    build:
      # the purpose of context one level above dockerfile
      # is to utilize shared code, specifically in db
      dockerfile: pacer_web/Dockerfile
      context: .
      # The dev instance still needs works, so default to base for now
      target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./pacer_web:/srv/pacer
      # create volumes for the build and node_modules so that
      # the resources are not copied back to the local host when
      # mounting.
      - /srv/pacer/build
      - /srv/pacer/node_modules
  worker:
    build:
      # the purpose of context one level above is to install the entire pacer package
      # and to copy the wait-for-it.sh and start_worker.sh files in the deploy directory
      dockerfile: pacer_worker/Dockerfile
      context: .
      target: dev
    volumes:
      - ./pacer_worker:/pacer/pacer_worker
      - ./tests:/pacer/tests
