[tool.poetry]
name = "pacer"
version = "1.0.0"
description = "Pacer web service converts building energy models in OpenStudio/EnergyPlus, Spawn of EnergyPlus, or Modelica to interactive virtual buildings."
authors = [
  'Kyle Benne <kyle.benne@nlr.gov>',
  'Anya Petersen <Anya.Petersen@nlr.gov>',
  'Nicholas Long <nicholas.long@nlr.gov>',
  'Tobias Shapinsky <tobias.shapinsky@nlr.gov>',
  'Alex Swindler <alex.swindler@nlr.gov>',
  'Tim Coleman <tim.coleman@nlr.gov>',
  'Cory Mosiman <cory.mosiman12@gmail.com>',
  'Brian Ball <brian.ball@nlr.gov>',
  'Willy Bernal <willy.bernalheredia@nlr.gov>',
]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11"

boto3 = "~1.26"
mongoengine = "~0.29"
pandas = "~2.2"
redis = "~4.5"

scipy = "~1.14"

# The influxdb dependency will be removed once filebeat is configured
influxdb = "^5.3.1"


[tool.poetry.group.dev.dependencies]
# required for tests to pass right now. There are often issues when pinning to a branch
# and calling poetry update. I have had to completely remove my venv and reinstall in order
# to get the latest updates.
alfalfa-client = "1.0.0"
# alfalfa-client = { git = "https://github.com/NatLabRockies/alfalfa-client.git", branch = "enhance_file_operations" }
autopep8 = "~2.0"
pre-commit = "~2.21"
pytest = "~7.2"
pycodestyle = "~2.10"
pytest-cov = "~4.0"
pytest-timeout = "~2.1"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
